version: '3'
services:
  web:
    container_name: nginx
    image: nginx:1.13.5-alpine
    ports:
      - 8081:80
    volumes:
      - ./uwsgi_nginx.conf:/etc/nginx/conf.d/default.conf

  uwsgi-node:
    container_name: uwsgi-node
    build: .
    expose:
      - 3031
    depends_on:
      - db
      - web
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres@db/flask
  db:
    container_name: pgsql-9.6.5
    image: postgres:9.6.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=flask

volumes:
  flask-pgsql: