"""empty message

Revision ID: 223d26b6ab0b
Revises: d17443e385a0
Create Date: 2017-11-04 15:28:02.805975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223d26b6ab0b'
down_revision = 'd17443e385a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_user', sa.Column('migration_test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_user', 'migration_test')
    # ### end Alembic commands ###
