"""empty message

Revision ID: 82273add3ca5
Revises: 2c6e8ef271eb
Create Date: 2017-11-04 15:24:47.148750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82273add3ca5'
down_revision = '2c6e8ef271eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_user', sa.Column('migration_test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_user', 'migration_test')
    # ### end Alembic commands ###
